name: Build Allure Report

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build-allure-report-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Allure Report
        run: | 
          wget https://repo1.maven.org/maven2/ru/yandex/qatools/allure/allure-commandline/1.5.4/allure-commandline-1.5.4-standalone.zip
          unzip allure-commandline-1.5.4-standalone.zip -d allure-commandline
          ./allure-commandline/bin/allure help
      - name: Generate Allure Report
        run: | 
          ./allure-commandline/bin/allure generate ./allure-results/v1
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-v1
          path: allure-report/
  build-allure-report-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Allure Report
        run: | 
          wget https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.zip
          unzip allure-commandline-2.30.0.zip
          ./allure-2.30.0/bin/allure --help
      - name: Generate Allure Report
        run: | 
          ./allure-2.30.0/bin/allure generate ./allure-results/v1 -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-v2
          path: allure-report/
  build-allure-report-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate Allure Report
        run: | 
          npx allure classic allure-results/v1 --single-file -o allure-report
          npx allure awesome allure-results/v2 --single-file -o allure-report
          npx allure log allure-results/v2 > allure-report/report.log
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-v3
          path: allure-report/
  aggregate: 
      runs-on: ubuntu-latest
      needs: [ build-allure-report-v1, build-allure-report-v2, build-allure-report-v3 ]
      steps:
        - name: Download Allure Report V1
          uses: actions/download-artifact@v4
          with:
            name: allure-report-v1
            path: allure-report/v1
        - name: Download Allure Report V2
          uses: actions/download-artifact@v4
          with:
            name: allure-report-v2
            path: allure-report/v2
        - name: Download Allure Report V2
          uses: actions/download-artifact@v4
          with:
            name: allure-report-v3
            path: allure-report/v3
        - name: Upload Allure Report
          id: deployment
          uses: actions/upload-pages-artifact@v3
          with:
            path: allure-report/
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: [ aggregate ]
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
