name: Build Allure Report

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build-allure-report-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Allure Report
        run: | 
          wget https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.zip
          unzip allure-commandline-2.30.0.zip
          ./allure-2.30.0/bin/allure --help
      - name: Generate Allure Report
        run: | 
          ./allure-2.30.0/bin/allure generate ./allure-results/v1 -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-v2
          path: allure-report/
  aggregate: 
      runs-on: ubuntu-latest
      needs: [ build-allure-report-v2 ]
      steps:
        - name: Download Allure Report V2
          uses: actions/download-artifact@v4
          with:
            name: allure-report-v2
            path: allure-report/v2
        - name: Upload Allure Report
          id: deployment
          uses: actions/upload-pages-artifact@v3
          with:
            path: allure-report/
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: [ aggregate ]
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
